import { readFile } from "node:fs/promises";
import path from "node:path";
import ts from "typescript";
import { listFilesRecursive, pathExists } from "./fs.js";

export type ToolMetadata = {
  filePath: string;
  importPath: string;
  importName: string;
  name: string;
  description: string;
};

export type ToolValidationResult = {
  tools: ToolMetadata[];
  errors: string[];
  warnings: string[];
};

const snakeCasePattern = /^[a-z][a-z0-9]*(?:_[a-z0-9]+)*$/;

export type DiscoverToolsOptions = {
  chatbotRoot?: string;
};

export function resolveChatbotRoot(cwd: string, options: DiscoverToolsOptions = {}) {
  return path.resolve(cwd, options.chatbotRoot ?? "chatbot");
}

export function readChatbotRoot(args: { flags?: Record<string, string | boolean> }) {
  const srcDir = typeof args.flags?.["src-dir"] === "string" ? args.flags["src-dir"] : undefined;
  const chatbotRoot = typeof args.flags?.["chatbot-root"] === "string" ? args.flags["chatbot-root"] : undefined;
  if (chatbotRoot) {
    return chatbotRoot;
  }

  return srcDir ? path.join(srcDir, "chatbot") : "chatbot";
}

export async function inferChatbotRoot(
  cwd: string,
  args: { flags?: Record<string, string | boolean> },
) {
  const explicit = readChatbotRoot(args);
  if (explicit !== "chatbot") {
    return explicit;
  }

  if (!(await pathExists(path.join(cwd, "chatbot"))) && (await pathExists(path.join(cwd, "src", "chatbot")))) {
    return path.join("src", "chatbot");
  }

  return explicit;
}

export async function discoverTools(
  cwd: string,
  options: DiscoverToolsOptions = {},
): Promise<ToolValidationResult> {
  const chatbotRoot = resolveChatbotRoot(cwd, options);
  const toolsRoot = path.join(chatbotRoot, "tools");
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!(await pathExists(toolsRoot))) {
    return { tools: [], errors, warnings };
  }

  const files = (await listFilesRecursive(toolsRoot))
    .filter((filePath) => filePath.endsWith(`${path.sep}index.ts`))
    .sort((left, right) => left.localeCompare(right));

  const tools = await Promise.all(
    files.map(async (filePath, index) =>
      parseToolFile(cwd, chatbotRoot, filePath, index, errors, warnings),
    ),
  );

  const seenNames = new Map<string, string>();
  for (const tool of tools) {
    if (!snakeCasePattern.test(tool.name)) {
      errors.push(`${relative(cwd, tool.filePath)}: tool name "${tool.name}" must be snake_case.`);
    }

    const previous = seenNames.get(tool.name);
    if (previous) {
      errors.push(
        `${relative(cwd, tool.filePath)}: duplicate tool name "${tool.name}" already used by ${previous}.`,
      );
    } else {
      seenNames.set(tool.name, relative(cwd, tool.filePath));
    }
  }

  return { tools, errors, warnings };
}

export function generateToolsFile(tools: ToolMetadata[]) {
  const imports = tools
    .map((tool) => `import ${tool.importName} from "${tool.importPath}";`)
    .join("\n");
  const list = tools.map((tool) => `  ${tool.importName},`).join("\n");
  const catalog = tools
    .map(
      (tool) => `  {
    name: ${JSON.stringify(tool.name)},
    description: ${JSON.stringify(tool.description)},
    path: ${JSON.stringify(tool.importPath)},
  },`,
    )
    .join("\n");

  return `/* eslint-disable */
// This file is generated by chatdock-sdk sync-tools. Do not edit manually.
${imports ? `\n${imports}\n` : ""}
export const tools = [
${list}
] as const;

export const toolCatalog = [
${catalog}
] as const;
`;
}

async function parseToolFile(
  cwd: string,
  chatbotRoot: string,
  filePath: string,
  index: number,
  errors: string[],
  warnings: string[],
): Promise<ToolMetadata> {
  const sourceText = await readFile(filePath, "utf8");
  const source = ts.createSourceFile(filePath, sourceText, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS);
  const relativePath = relative(cwd, filePath);
  const defaultExpression = findDefaultExportExpression(source);

  if (!defaultExpression) {
    errors.push(`${relativePath}: expected a default export created with defineTool({...}).`);
  }

  const objectLiteral = defaultExpression ? unwrapDefineToolObject(defaultExpression) : undefined;
  if (!objectLiteral) {
    errors.push(`${relativePath}: default export must be defineTool({...}) or an object literal.`);
  }

  const name = objectLiteral ? readStringProperty(objectLiteral, "name") : undefined;
  const description = objectLiteral ? readStringProperty(objectLiteral, "description") : undefined;

  for (const required of ["name", "description", "execute"]) {
    if (!objectLiteral || !hasProperty(objectLiteral, required)) {
      errors.push(`${relativePath}: missing required property "${required}".`);
    }
  }
  if (!objectLiteral || (!hasProperty(objectLiteral, "inputSchema") && !hasProperty(objectLiteral, "input"))) {
    errors.push(`${relativePath}: missing required property "inputSchema".`);
  }

  if (!description) {
    errors.push(`${relativePath}: "description" must be a string literal for catalog generation.`);
  } else if (description.length > 180) {
    warnings.push(`${relativePath}: description is longer than 180 characters.`);
  }

  return {
    filePath,
    importPath: toImportPath(path.relative(chatbotRoot, path.dirname(filePath))),
    importName: `tool${index + 1}`,
    name: name ?? `invalid_tool_${index + 1}`,
    description: description ?? "",
  };
}

function findDefaultExportExpression(source: ts.SourceFile): ts.Expression | undefined {
  for (const statement of source.statements) {
    if (ts.isExportAssignment(statement)) {
      return statement.expression;
    }

    if (
      ts.isVariableStatement(statement) &&
      statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) &&
      statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.DefaultKeyword)
    ) {
      return statement.declarationList.declarations[0]?.initializer;
    }

    if (
      ts.isFunctionDeclaration(statement) &&
      statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) &&
      statement.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.DefaultKeyword)
    ) {
      return undefined;
    }
  }

  return undefined;
}

function unwrapDefineToolObject(expression: ts.Expression): ts.ObjectLiteralExpression | undefined {
  if (ts.isObjectLiteralExpression(expression)) {
    return expression;
  }

  if (ts.isCallExpression(expression)) {
    const firstArgument = expression.arguments[0];
    if (firstArgument && ts.isObjectLiteralExpression(firstArgument)) {
      return firstArgument;
    }
  }

  return undefined;
}

function hasProperty(objectLiteral: ts.ObjectLiteralExpression, propertyName: string) {
  return objectLiteral.properties.some((property) => propertyNameOf(property.name) === propertyName);
}

function readStringProperty(objectLiteral: ts.ObjectLiteralExpression, propertyName: string) {
  const property = objectLiteral.properties.find((candidate) => propertyNameOf(candidate.name) === propertyName);
  if (!property || !ts.isPropertyAssignment(property)) {
    return undefined;
  }

  const initializer = property.initializer;
  return ts.isStringLiteral(initializer) || ts.isNoSubstitutionTemplateLiteral(initializer)
    ? initializer.text
    : undefined;
}

function propertyNameOf(name: ts.PropertyName | undefined) {
  if (!name) {
    return undefined;
  }

  if (ts.isIdentifier(name) || ts.isStringLiteral(name) || ts.isNumericLiteral(name)) {
    return name.text;
  }

  return undefined;
}

function toImportPath(relativeDirectory: string) {
  const normalized = relativeDirectory.split(path.sep).join("/");
  return normalized.startsWith(".") ? normalized : `./${normalized}`;
}

function relative(cwd: string, filePath: string) {
  return path.relative(cwd, filePath).split(path.sep).join("/");
}
